services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      # Primary superuser for administrative tasks
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPERUSER_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB}
      # Performance tuning
      POSTGRES_MAX_CONNECTIONS: ${POSTGRES_MAX_CONNECTIONS:-100}
      POSTGRES_SHARED_BUFFERS: ${POSTGRES_SHARED_BUFFERS:-256MB}
      POSTGRES_EFFECTIVE_CACHE_SIZE: ${POSTGRES_EFFECTIVE_CACHE_SIZE:-1GB}
      PGPASSWORD: ${POSTGRES_SUPERUSER_PASSWORD}
      RESTAURANT_DB_PASSWORD: ${RESTAURANT_DB_PASSWORD}
      AIRFLOW_DB_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      ANALYTICS_READONLY_PASSWORD: ${ANALYTICS_READONLY_PASSWORD}
      # Timezone
      TZ: ${TZ:-UTC}
      PGTZ: ${TZ:-UTC}
    volumes:
      - ${POSTGRES_DATA_PATH:-./data/postgres}:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_SUPERUSER} -d ${POSTGRES_DEFAULT_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
